### ISSUE TITLE
legacy: remove precached values for logged in user

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-ext#3]
Can we remove the [precached values](https://github.com/inveniosoftware/invenio-ext/blob/master/invenio_ext/login/legacy_user.py#L169)? 

I found a message `compatibility layer only`. They are still necessary or we can simply remove them?

I found they are used here:
 - [ ] invenio-deposit/invenio_deposit/models.py

`564:        auth_types = user_info.get('precached_allowed_deposition_types', set())`

- [ ] invenio-deposit/invenio_deposit/restful.py

`158:    return type_ in current_user.get('precached_allowed_deposition_types', [])`

- [ ] invenio-search/invenio_search/facet_builders.py

`61:            current_user.get('precached_permitted_restricted_collections', []),`

- [ ] invenio-search/invenio_search/enhancers/collection_filter.py

`111:        'precached_permitted_restricted_collections', [])`

- [ ] invenio-formatter/invenio_formatter/templates/format/record/Default_HTML_MARC.tpl

`20:<pre>{{ tfn_get_fieldvalues_alephseq_like(recid, [], current_user.get('precached_canseehiddenmarctags', False))|safe }}</pre>`

- [ ] invenio-formatter/invenio_formatter/templates/format/record/Default_text_MARC.tpl

`1:{{ tfn_get_fieldvalues_alephseq_like(recid, [], current_user.get('precached_canseehiddenmarctags', False))|safe }}`

@jirikuncar

**Comment by jirikuncar** [comment]
@hachreak in general they are still required by they should be populated using signals (see https://github.com/inveniosoftware/invenio/issues/3438).

**Comment by jirikuncar** [comment]
Caching is happening on per-package basis (e.g. Invenio-Access).
